### ISSUE TITLE
getSwaps() returnAmount mismatch with on-chain result

### ISSUE THREAD

**Issue by dongwookang95** [balancer-labs/balancer-sor#326]
I recently updated from balancer-sor 2.0.0-beta.0 to 4.0.1-beta.13 to get off-chain quote. It used to work properly(matched on/off chain quote) before the update, and no logic has been changed apart from the upgrade. Followings are the code that I am using to call getSwap() function and error examples.

`const swapInfo = await sor.getSwaps(token0Address, token1Address, SwapTypes.SwapExactIn, swapAmount, {
    gasPrice: BigNumber.from('40000000000'),
    maxPools: 4,
    poolTypeFilter: PoolFilter.All,
    forceRefresh: false,
  });`

`{
      "poolId": "0x2f4eb100552ef93840d5adc30560e5513dfffacb000000000000000000000334",
      "failMessage": "should swap 1.0 USDT for bb-a-USDT",
      "errorMessage": "[BalancerV2-bb-a-USDT-USDT-0x2f4eb100552ef93840d5adc30560e5513dfffacb000000000000000000000334] expected: 0.996741477812543832 bb-a-USDT - actual: 0.996741471157526565 bb-a-USDT - error: -0.000000006655017267 bb-a-USDT: Expected \"996741471157526565\" to be equal 996741477812543832"
    },
    {
      "poolId": "0x25accb7943fd73dda5e23ba6329085a3c24bfb6a000200000000000000000387",
      "failMessage": "should swap 1.0 wstETH for bb-a-USD",
      "errorMessage": "[BalancerV2-wstETH-bb-a-USD-0x25accb7943fd73dda5e23ba6329085a3c24bfb6a000200000000000000000387] expected: 1258.805945837242429336 bb-a-USD - actual: 1258.805945977795458677 bb-a-USD - error: 0.000000140553029341 bb-a-USD: Expected \"1258805945977795458677\" to be equal 1258805945837242429336"
    },`

Would be much appreciative if the team can provide some suspicious point that I can take a look.

Thank you in advance!

**Comment by johngrantuk** [comment]
Hi. Thanks for the info.
I think this may be related to using an outdated priceRate value but we would have to debug further. In the meantime maybe you could use queryBatchSwap with the swap info to get the accurate onchain value.

**Comment by dongwookang95** [comment]
Thanks for your suggrestion. I've tried with queryBatchSwap function. It halved the number of errored pools, but still receiving errors. My implementation is following : 

`const swaps: BatchSwapStep[] = [
    {
      poolId: poolInfo.id,
      assetInIndex: 0,
      assetOutIndex: 1,
      amount: amount0In.toString(),
      userData: "0x",
    },
  ];

  const assets: string[] = [token0, token1];
  const swapInfoTest = await balancer.swaps.queryBatchSwap({
    kind: swapType,
    swaps,
    assets,
  });`

The token0 and token1 are representing each token's address, and the swapType was set to SwapExactIn. What could be causing this errors? The difference between actual amount returned and queryBatchSwap results are usually less than 0.1%. I will attach the pools with the error. 
[batchswapError.json.zip](https://github.com/balancer-labs/balancer-sor/files/10189478/batchswapError.json.zip)

**Comment by dongwookang95** [comment]
Hi @sergioyuhjtman, Thanks for the reply. 

To clarify the batchswapError.json was comparison results between [queryBatchSwap() ](https://etherscan.io/address/0xba12222222228d8ba445958a75a0704d566bf2c8#writeContract#F8)and [swap()](https://etherscan.io/address/0xba12222222228d8ba445958a75a0704d566bf2c8#writeContract#F14). About the time delay between the queryBatchSwap() and Swap(), I fork at block#16217540 , then execute queryBatchSwap() at 16217540  and swap() at 16217541 respectively. However, I found queryBatchSwap is callstatic function which means it won't affect on the state to calculate the price calculation parameters. So that I don't think it is the problem related to time/block difference.

 I will add the difference error between getSwap() from SOR and swap() form contract as well. The forked block number is 16217628. 

Thank you in advance.



[errors.zip](https://github.com/balancer-labs/balancer-sor/files/10259936/errors.zip)

**Comment by dongwookang95** [comment]
Issue is resolved from 4.1.1 update
