### ISSUE TITLE
Pushing to NPM

### ISSUE THREAD

**Issue by mdcoon** [balancer-labs/balancer-sor#52]
Is there a reason this isn't pushed to npm? Or if it is, it isn't published under @balancer-labs. I'd like to use the latest version that follows the example code but unless I'm building it inside my project, seems to be unavailable.

**Comment by johngrantuk** [comment]
@mdcoon the latest version will be tagged in npm shortly. In the meantime you can install using: @balancer-labs/sor@1.0.0-1.
