### ISSUE TITLE
Typo in example-swapExactOut

### ISSUE THREAD

**Issue by shresthagrawal** [balancer-labs/balancer-sor#53]
According to what I understand for `swapExactOut` in the function `getCostOutputToken` we need to  pass `tokenIn`. If so there is a typo in the below code. It should be `USDC` instead of `DAI` 

https://github.com/balancer-labs/balancer-sor/blob/1d06567831ec688b98026b20057b8557b786daac/test/testScripts/example-swapExactOut.ts#L25

**Comment by johngrantuk** [comment]
This was indeed an error. Thanks for pointing that out, it's corrected now.
